import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
test('Postgres enforces ownership, limits, dates, and deletion cascades',async()=>{
 const db=new PGlite();
 await db.exec(`create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to authenticated;grant execute on function auth.uid() to authenticated;`);
 await db.exec(readFileSync(new URL('../supabase/migrations/202609260001_fivefold.sql',import.meta.url),'utf8'));
 const a='00000000-0000-4000-8000-000000000001',b='00000000-0000-4000-8000-000000000002';
 await db.query('insert into auth.users values ($1),($2)',[a,b]);
 const owner=async id=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec('set role authenticated');};
 const action=async input=>(await db.query('select public.tracker_action($1::jsonb) as state',[JSON.stringify({timezone:'UTC',...input})])).rows[0].state;
 const state=async()=>(await db.query("select public.tracker_state('UTC') as state")).rows[0].state;
 await owner(a);let s;
 for(let i=0;i<5;i++)s=await action({action:'create',name:'Habit '+i});
 assert.equal(s.habits.length,5);await assert.rejects(action({action:'create',name:'Sixth'}),/up to five/);
 const habit=s.habits[0];
 await action({action:'complete',id:habit.id,day:s.today,completed:true});await action({action:'complete',id:habit.id,day:s.today,completed:true});assert.equal((await state()).completions.length,1);
 await assert.rejects(action({action:'complete',id:habit.id,day:'2999-01-01',completed:true}),/Choose a date/);
 await assert.rejects(action({action:'complete',id:habit.id,day:s.today,completed:'true'}),/Invalid check/);
 await assert.rejects(action({action:'rename',id:habit.id,name:{malformed:true}}),/habit name/);
 await assert.rejects(db.query("insert into public.habits(user_id,slot,name,created_date) values($1,1,'bypass',current_date)",[b]),/permission denied/);
 await owner(b);assert.equal((await state()).habits.length,0);assert.equal((await db.query('select * from public.habits')).rows.length,0);assert.equal((await db.query('select * from public.completions')).rows.length,0);
 for(const actionName of ['rename','delete','complete'])await assert.rejects(action({action:actionName,id:habit.id,name:'stolen',day:s.today,completed:true}),/Habit not found/);
 await action({action:'create',name:'B stays'});
 await db.exec('reset role');await db.query('delete from auth.users where id=$1',[a]);
 assert.equal((await db.query('select * from public.completions')).rows.length,0);assert.equal((await db.query('select * from public.habits')).rows.length,1);assert.equal((await db.query('select * from public.profiles')).rows.length,1);
 await owner(a);await assert.rejects(state(),/sign in again/);await assert.rejects(action({action:'create',name:'deleted token'}),/sign in again/);
 await db.exec('reset role;set role anon');await assert.rejects(state(),/permission denied/);await db.close();
});
