'use client';
import {useState,useEffect} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
export function AccountSettings({googleAccount}:{googleAccount:boolean}){
 const [open,setOpen]=useState(false),[password,setPassword]=useState(''),[confirmation,setConfirmation]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [verified,setVerified]=useState(false);useEffect(()=>{if(new URLSearchParams(location.search).get('delete')==='confirm'){setOpen(true);setVerified(true);history.replaceState(null,'','/');}},[]);
 return <><button className="icon-button" onClick={()=>setOpen(true)}>Account settings</button><Dialog open={open} onOpenChange={v=>{if(!busy){setOpen(v);setVerified(false);setPassword('');setConfirmation('');setError('');}}}><DialogContent><DialogHeader><DialogTitle>Delete your account</DialogTitle><DialogDescription>Permanently delete your login, all five habits, and every check-in from this app. This cannot be undone. Provider backups may remain until their normal expiry.</DialogDescription></DialogHeader><form className="dialog-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/account',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({password,confirmation})});const b=await r.json() as {ok?:boolean;error?:string;message?:string};if(r.status===403)setVerified(false);if(!r.ok)throw new Error(b.error||'Deletion failed.');location.assign('/login?deleted=1');}catch(e){setError(e instanceof Error?e.message:'Please try again.');setBusy(false);}}}>
 {googleAccount?<div>{verified?<p>Google confirmation received. Type DELETE below within five minutes to finish.</p>:<a className="secondary" href="/auth/google?reauth=delete">Confirm identity with Google</a>}</div>:<label>Current password<input type="password" autoComplete="current-password" required maxLength={128} disabled={busy} value={password} onChange={e=>setPassword(e.target.value)}/></label>}<label>Type DELETE to confirm<input autoComplete="off" required disabled={busy} value={confirmation} onChange={e=>setConfirmation(e.target.value)}/></label>{error&&<p role="alert" className="notice">{error}</p>}<div className="dialog-actions"><button className="secondary" type="button" disabled={busy} onClick={()=>{setOpen(false);setVerified(false);setPassword('');setConfirmation('');}}>Cancel</button><button className="danger" disabled={busy||confirmation!=='DELETE'||(googleAccount?!verified:!password)}>{busy?'Deleting…':'Permanently delete account'}</button></div>
 </form></DialogContent></Dialog></>;
}
